### ISSUE TITLE
Error Deploying

### ISSUE THREAD

**Issue by oneironaut2209** [ksssomesh12/tgmb-beta#1]
Getting this build error on Heroku:

>  -----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
-----> No Python version was specified. Using the buildpack default: python-3.9.6
       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
cp: cannot stat '/tmp/build_c317441a/requirements.txt': No such file or directory
-----> Installing python-3.9.6
-----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Obtaining file:///tmp/build_c317441a (from -r /tmp/build_c317441a/requirements.txt (line 1))
           ERROR: Command errored out with exit status 1:
            command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/build_c317441a/setup.py'"'"'; __file__='"'"'/tmp/build_c317441a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8rpf8_5h
                cwd: /tmp/build_c317441a/
           Complete output (5 lines):
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/build_c317441a/setup.py", line 1, in <module>
               import googleapiclient.discovery
           ModuleNotFoundError: No module named 'googleapiclient'
           ----------------------------------------
       ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by ksssomesh12** [comment]
> Getting this build error on Heroku:
> 
> > -----> Building on the Heroku-20 stack
> > -----> Determining which buildpack to use for this app
> > -----> Python app detected
> > -----> No Python version was specified. Using the buildpack default: python-3.9.6
> > To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
> > cp: cannot stat '/tmp/build_c317441a/requirements.txt': No such file or directory
> > -----> Installing python-3.9.6
> > -----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
> > -----> Installing SQLite3
> > -----> Installing requirements with pip
> > Obtaining file:///tmp/build_c317441a (from -r /tmp/build_c317441a/requirements.txt (line 1))
> > ERROR: Command errored out with exit status 1:
> > command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/build_c317441a/setup.py'"'"'; **file**='"'"'/tmp/build_c317441a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8rpf8_5h
> > cwd: /tmp/build_c317441a/
> > Complete output (5 lines):
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/tmp/build_c317441a/setup.py", line 1, in 
> > import googleapiclient.discovery
> > ModuleNotFoundError: No module named 'googleapiclient'
> > ----------------------------------------
> > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> > !     Push rejected, failed to compile Python app.
> > !     Push failed

Set stack to container on heroku

**Comment by oneironaut2209** [comment]
![image](https://user-images.githubusercontent.com/63645932/124719285-9c5ba300-df24-11eb-8e78-bb69a5b1edba.png)

**Comment by ksssomesh12** [comment]
Hold On. I forgot to add `heroku.yml` to the deploy folder. SideNote: U need to run the `setup.py` in deploy folder before u deploy anywhere. Make `config.env` from `config_sample.env` in deploy folder. Dont deploy from the repository root.

**Comment by oneironaut2209** [comment]
Yes I am deploying from deploy folder. token.json is also generated with creds.json. and config.env is also ok.

**Comment by ksssomesh12** [comment]
> Yes I am deploying from deploy folder. token.json is also generated with creds.json. and config.env is also ok.

Check now in deploy folder

**Comment by oneironaut2209** [comment]
Deployed successfully and working perfectly. Progress bar and index link should be added next 👍

**Comment by oneironaut2209** [comment]
![image](https://user-images.githubusercontent.com/63645932/124723321-8d76ef80-df28-11eb-825a-69b4e48abbb3.png)


This thing interferes with other bot's commands

**Comment by ksssomesh12** [comment]
> ![image](https://user-images.githubusercontent.com/63645932/124723321-8d76ef80-df28-11eb-825a-69b4e48abbb3.png)
> 
> This thing interferes with other bot's commands

As I said earlier, currently the functionality is very limited. And that doesn't interfere with other bot commands really. That means that whatever bot command u are trying to use is not implemented as of yet.
Currently only aria downloads and google drive uploads work. And without no issues at all. No extraction / compression functionality yet.
