### ISSUE TITLE
How to deploy? and THANKS

### ISSUE THREAD

**Issue by askfriends** [ksssomesh12/tgmb-beta#24]
HI;
i hope its ready to deploy now, so will u plz add some instructions regarding how to deploy it and what features it has.
Thanks for bringing this up.

**Comment by AmirulAndalib** [comment]
> HI; i hope its ready to deploy now, so will u plz add some instructions regarding how to deploy it and what features it has. Thanks for bringing this up.

use brain.exe cuz heroku banning it

**Comment by askfriends** [comment]
> > HI; i hope its ready to deploy now, so will u plz add some instructions regarding how to deploy it and what features it has. Thanks for bringing this up.
> 
> use brain.exe cuz heroku banning it

My brain.exe is not that capable thats why im asking here.
i have another bot from other repo which is working fine, so there must be a way to fix it.

**Comment by ksssomesh12** [comment]
Guys, my own bot got suspended on heroku. So, I'm confused ri8 now.

**Comment by AmirulAndalib** [comment]
> Guys, my own bot got suspended on heroku. So, I'm confused ri8 now.

yes all bots being banned not only yours .............................Bettter if you rebase code and use fresh docker with alpine debian arch or fedora

**Comment by ksssomesh12** [comment]
> HI; i hope its ready to deploy now, so will u plz add some instructions regarding how to deploy it and what features it has. Thanks for bringing this up.

Fork this repo [tgmb-beta-deploy](https://github.com/ksssomesh12/tgmb-beta-deploy). Dont make any changes to code base. Go to repository settings and add secrets in accordance with ./github/workflows/deploy-heroku.yml file. Detailed instructions will be added some time soon after fixing suspension by heroku.

**Comment by askfriends** [comment]
> > HI; i hope its ready to deploy now, so will u plz add some instructions regarding how to deploy it and what features it has. Thanks for bringing this up.
> 
> Fork this repo [tgmb-beta-deploy](https://github.com/ksssomesh12/tgmb-beta-deploy). Dont make any changes to code base. Go to repository settings and add secrets in accordance with ./github/workflows/deploy-heroku.yml file. Detailed instructions will be added some time soon after fixing suspension by heroku.

Thanks bro, will try this.

**Comment by askfriends** [comment]
@ksssomesh12  any update?

**Comment by ksssomesh12** [comment]
> @ksssomesh12 any update?

Added support for qbittorrent.

**Comment by askfriends** [comment]
> > @ksssomesh12 any update?
> 
> Added support for qbittorrent.

Thanks bro, but readme is still missing, will u add some info there?

EDIT: 
there is little confusion, there is no config file there, so where to copy paste these values?
i only see 'HEROKU_APP_NAME' and 'HEROKU_API_KEY' in https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml

**Comment by sentinm** [comment]
> > > @ksssomesh12 any update?
> > 
> > 
> > Added support for qbittorrent.
> 
> Thanks bro, but readme is still missing, will u add some info there?
> 
> EDIT: there is little confusion, there is no config file there, so where to copy paste these values? i only see 'HEROKU_APP_NAME' and 'HEROKU_API_KEY' in https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml

It's github secrets  <your_fork> -> settings -> secrets -> add new

**Comment by askfriends** [comment]
> > > > @ksssomesh12 any update?
> > > 
> > > 
> > > Added support for qbittorrent.
> > 
> > 
> > Thanks bro, but readme is still missing, will u add some info there?
> > EDIT: there is little confusion, there is no config file there, so where to copy paste these values? i only see 'HEROKU_APP_NAME' and 'HEROKU_API_KEY' in https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml
> 
> It's github secrets <your_fork> -> settings -> secrets -> add new

yes bro but what about config.env var name, is it DYNAMIC_JSON_FILEID ?

**Comment by sentinm** [comment]
> > > > > @ksssomesh12 any update?
> > > > 
> > > > 
> > > > Added support for qbittorrent.
> > > 
> > > 
> > > Thanks bro, but readme is still missing, will u add some info there?
> > > EDIT: there is little confusion, there is no config file there, so where to copy paste these values? i only see 'HEROKU_APP_NAME' and 'HEROKU_API_KEY' in https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml
> > 
> > It's github secrets <your_fork> -> settings -> secrets -> add new
> 
> yes bro but what about config.env var name, is it DYNAMIC_JSON_FILEID ?

There is a sample for every env check all the files in the repository. [links](https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/setup.py#L472-L479)

And you should upload it to googledrive and get the fileid of it, as it is taken in here. [links](https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml#L32)

**Comment by ksssomesh12** [comment]
> > > > > > @ksssomesh12 any update?
> > > > > 
> > > > > 
> > > > > Added support for qbittorrent.
> > > > 
> > > > 
> > > > Thanks bro, but readme is still missing, will u add some info there?
> > > > EDIT: there is little confusion, there is no config file there, so where to copy paste these values? i only see 'HEROKU_APP_NAME' and 'HEROKU_API_KEY' in https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml
> > > 
> > > 
> > > It's github secrets <your_fork> -> settings -> secrets -> add new
> > 
> > 
> > yes bro but what about config.env var name, is it DYNAMIC_JSON_FILEID ?
> 
> There is a sample for every env check all the files in the repository. [links](https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/setup.py#L472-L479)
> 
> And you should upload it to googledrive and get the fileid of it, as it is taken in here. [links](https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml#L32)

Thank You. And Sorry. ReadMe is in works. And U dont have to generate any json files by urself. The setup.py script will do that for you.

**Comment by sentinm** [comment]
> > > > > > > @ksssomesh12 any update?
> > > > > > 
> > > > > > 
> > > > > > Added support for qbittorrent.
> > > > > 
> > > > > 
> > > > > Thanks bro, but readme is still missing, will u add some info there?
> > > > > EDIT: there is little confusion, there is no config file there, so where to copy paste these values? i only see 'HEROKU_APP_NAME' and 'HEROKU_API_KEY' in https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml
> > > > 
> > > > 
> > > > It's github secrets <your_fork> -> settings -> secrets -> add new
> > > 
> > > 
> > > yes bro but what about config.env var name, is it DYNAMIC_JSON_FILEID ?
> > 
> > There is a sample for every env check all the files in the repository. [links](https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/setup.py#L472-L479)
> > 
> > And you should upload it to googledrive and get the fileid of it, as it is taken in here. [links](https://github.com/ksssomesh12/tgmb-beta-deploy/blob/master/.github/workflows/deploy-heroku.yml#L32)
> 
> Thank You. And Sorry. ReadMe is in works. And U dont have to generate any json files by urself. The setup.py script will do that for you.

Oh ok, I had a little doubt that setup.py has an automation of generating configs.

**Comment by aditya-shri** [comment]
I tried deploying from cli and it got deployed but its not responding to bot messages.

I think the problem might be in the config file.
The authorised chat and google folder section is not explained correctly.

if possible, please add instruction to create the config file for the deployment.

**Comment by askfriends** [comment]
any update bro?
