### ISSUE TITLE
Error with setup.py

### ISSUE THREAD

**Issue by oneironaut2209** [ksssomesh12/tgmb-beta#8]
I tried to deply from deploy folder and also installed reqiurements.txt  with pip3. I  am getting this error while running setup.py :

![image](https://user-images.githubusercontent.com/63645932/129160306-db9e06f3-4215-4a9b-a47c-a8a07d904c94.png)

**Comment by ksssomesh12** [comment]
The issue is resolved. Try this branch [bugfix-#8](https://github.com/ksssomesh12/tgmb-beta/tree/bugfix-%238) and confirm the same. Cheers!

**Comment by oneironaut2209** [comment]
Yes it worked. Merge with master. Thanks for that Folder upload feature. Really needed that thing. :+1:

**Comment by ksssomesh12** [comment]
> Yes it worked. Merge with master. Thanks for that Folder upload feature. Really needed that thing. 👍

It will be merged later. Well, u asked for it in the old repo. Status msg will be updated next. I'm actually surprised that u deployed successfully without the readme file.

**Comment by oneironaut2209** [comment]
Yeh I figured out everything. Do you need any help with readme ? I can write a guide to deploy from linux/wsl . (for heroku)
Also idk if it is deployable from windows.

**Comment by ksssomesh12** [comment]
> Yeh I figured out everything. Do you need any help with readme ? I can write a guide to deploy from linux/wsl . (for heroku)
> Also idk if it is deployable from windows.

Help is appreciated much. But at this point, I want to do everything from scratch initially by myself to be a cut above lzzy12's python-aria-mirror-bot. You might have noticed the codebase is completely new and different. So, let me just work on it one at a time. Concerning deployments, no the repo is not deployable on windows platforms. Keep Testing!
